trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: alecmocatta/azure-pipeline-templates
      endpoint: alecmocatta

jobs:
- template: rust.yml@templates
  parameters:
    default:
      rust_toolchain: 1.21.0 stable beta nightly
      rust_lint_toolchain: nightly-2019-07-19
      rust_flags: ''
      rust_features: ';default;all'
      rust_target_check: ''
      rust_target_build: ''
      rust_target_run: ''
    matrix:
      windows:
        imageName: 'vs2017-win2016'
        rust_target_run: 'x86_64-pc-windows-msvc'
      mac:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin'
      linux:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu x86_64-unknown-linux-musl'
